const BASE_DIR_IMAGE = '/images/'

export const list = [
    {
        name: "Indomie Goreng Rendang",
        desc: "Masakan Instan Terenak di Dunia",
        longDesc: "Indomie Goreng rasa Rendang 3000.an dengan berbagai topping:<br>- potongan daging Wagyu A6 A6 joz<br>- tamago (telur, --jepang)<br>- Cabbage (kubis, --jaksel)<br>- chili slices (artiin sendiri)",
        stock: 10,
        price: 3900,
        src: BASE_DIR_IMAGE + "indomie-rendang.jpg",
    },
    {
        name: "Mie Gelas Rendang",
        desc: "Masakan Instan Khusus Anak Kostan",
        longDesc: "Mie homemade icik iwir disajikan dalam gelas (cup) rasa bumbu rendang asli, pedas dengan topping:<br>-ayam suwir<br>- saus padang<br>- potongan cabe<br>- bawang goreng",
        stock: 3,
        price: 1500,
        src: BASE_DIR_IMAGE + "mie-gelas.jpg",
    },
    {
        name: "Bakmi Mewah",
        desc: "Kalau Anak Kosan Jangan Macem-Macem Deh",
        longDesc: "Bakmi mewah dua bungkus dicampur dengan bumbu rahasia (gimmick) beserta topping<br>- dried meatball<br>- nori",
        stock: 80,
        price: 10000,
        src: BASE_DIR_IMAGE + "bakmi-mewah.jpg",
    },
    {
        name: "Sarden BCA",
        desc: "Makan Ikan biar Lulus Bootcamp Inosoft",
        longDesc: "Sarden kaleng(an) disajikan (di piring, dimana lagi? kamu nanyea?) dengan tumis lobak dan ekstra saus tomat rahasia (gimmick juga)",
        stock: 7,
        price: 7300,
        src: BASE_DIR_IMAGE + "sarden-bca.jpg",
    },
    {
        name: "Mixsuek",
        desc: "Ice Cream Republik Rakyat Pancasila wiuwiuwiu",
        longDesc: "Vanilla sundae dengan cream toping boba, choco chips dan strawberry paste",
        stock: 5,
        price: 5000,
        src: BASE_DIR_IMAGE + "mixsuek.jpg",
    },
    {
        name: "Smashed Chicken",
        desc: "Makanan yang sejam scroll g*food ujung-ujungnya juga ini",
        longDesc: "Ayam geprek hot uhuy sambal bawang dengan timun dan tomat, level pedas request langsung ke kasir",
        stock: 19,
        price: 12000,
        src: BASE_DIR_IMAGE + "smashed-chicken.png",
    },
    {
        name: "Setarmas Hot Americano Gula Aren plus Troffle",
        desc: "Minuman kopi pengguna nMac dan iSiteru, mantappu jiwaaaaa",
        longDesc: "Americano gula aren, diaduk clockwise 3 kali khusus kaum elit, ekspatriat, influencer, dan punya KTP jaksel. Kaum checkout nunggu diskon minggir dulu",
        stock: 13,
        price: 29800,
        src: BASE_DIR_IMAGE + "setarbak.jpg",
    },
]